project_name: litemv
version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

builds:
  - id: binaries
    binary: litemv-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: .
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0

nfpms:
  - id: litemv
    package_name: litemv
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Interlynk
    homepage: https://interlynk.io
    maintainer: Interlynk Authors hello@interlynk.io
    builds:
      - binaries
    description: Transfer SBOM's between different systems.
    license: "Apache License 2.0"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: /usr/bin/litemv-{{ .Os }}-{{ .Arch }}
        dst: /usr/bin/litemv
        type: "symlink"

archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow
  draft: true

sboms:
  - artifacts: binary
    documents:
      - "${artifact}.cdx.sbom.json"
    args: ["$artifact", "--output", "cyclonedx-json=$document"]
