---
name: Build SBOM | Augment | Enrich | Release

on:
  release:
    types:
      - published

permissions:
  contents: write

env:
  TOOL_NAME: ${{ github.repository }}
  SBOM_ENV: default
  PARLAY_VERSION: 0.8.0
  SBOMASM_VERSION: 1.0.8
  SBOMQS_VERSION: 1.2.0
  TRIVY_VERSION: 0.66.0
  SBOMMV_VERSION: 0.0.9

jobs:
  Generate:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.latest.outputs.tag }}
    steps:
      - name: Install Trivy
        run: |
          curl -L -o /tmp/trivy.tgz \
            "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz"
          tar xvf /tmp/trivy.tgz -C /tmp
          chmod +x /tmp/trivy

      - name: Get latest release tag
        id: latest
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/viveksahu26/litemv/releases/latest | jq -r .tag_name)
          echo "tag=${LATEST_TAG}" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT

      - name: Download litemv release
        run: |
          curl -L -o /tmp/litemv.tgz \
            "https://github.com/viveksahu26/litemv/archive/refs/tags/${{ steps.latest.outputs.tag }}.tar.gz"
          mkdir -p /tmp/litemv-src
          tar -xvzf /tmp/litemv.tgz -C /tmp/litemv-src --strip-components=1

      - name: Generate SBOM with Trivy
        run: |
          /tmp/trivy fs \
            --timeout 30m0s \
            --parallel 0 \
            --format cyclonedx \
            --skip-db-update \
            --offline-scan \
            --output /tmp/generated-litemv-sbom.cdx.json \
            /tmp/litemv-src

          /tmp/trivy fs \
            --timeout 30m0s \
            --parallel 0 \
            --format spdx-json \
            --skip-db-update \
            --offline-scan \
            --output /tmp/generated-litemv-sbom.spdx.json \
            /tmp/litemv-src

      - name: Upload Generated SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: generated-sboms
          path: |
            /tmp/generated-litemv-sbom.cdx.json
            /tmp/generated-litemv-sbom.spdx.json
          if-no-files-found: error

  Augment:
    runs-on: ubuntu-latest
    needs: Generate
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: generated-sboms

      - name: Install sbomasm
        run: |
          curl -L -o /tmp/sbomasm \
            "https://github.com/interlynk-io/sbomasm/releases/download/v${SBOMASM_VERSION}/sbomasm-linux-amd64"
          chmod +x /tmp/sbomasm

      - name: Augment SPDX
        run: |
          /tmp/sbomasm edit --append --subject Document \
              --author 'Interlynk Engineering' \
              --supplier 'litemv project (https://github.com/viveksahu26/litemv)' \
              --license 'Apache-2.0' \
              generated-litemv-sbom.spdx.json > augmented-litemv-sbom.spdx.json

          /tmp/sbomasm edit --subject primary-component \
              --supplier 'litemv project' \
              --repository 'https://github.com/viveksahu26/litemv.git' \
              --license 'Apache-2.0' \
              augmented-litemv-sbom.spdx.json > /tmp/augmented-litemv-sbom.spdx.json

      - name: Augment CycloneDX
        run: |
          /tmp/sbomasm edit --subject Document \
              --author 'Interlynk Engineering' \
              --supplier 'litemv project (https://github.com/viveksahu26/litemv)' \
              --lifecycle 'pre-build' \
              --repository 'https://github.com/viveksahu26/litemv.git' \
              --license 'Apache-2.0' \
              generated-litemv-sbom.cdx.json > augmented-litemv-sbom.cdx.json

          /tmp/sbomasm edit --subject primary-component \
              --author 'Interlynk Engineering' \
              --supplier 'litemv project' \
              --repository 'https://github.com/viveksahu26/litemv.git' \
              --license 'Apache-2.0' \
              augmented-litemv-sbom.cdx.json > /tmp/augmented-litemv-sbom.cdx.json

      - name: Upload Augmented SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: augmented-sboms
          path: |
            /tmp/augmented-litemv-sbom.spdx.json
            /tmp/augmented-litemv-sbom.cdx.json

  Enrich:
    runs-on: ubuntu-latest
    needs: Augment
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: augmented-sboms

      - name: Install parlay
        run: |
          curl -Ls https://github.com/snyk/parlay/releases/download/v${PARLAY_VERSION}/parlay_Linux_x86_64.tar.gz | tar xvz -C /tmp
          chmod +x /tmp/parlay

      - name: Enrich CycloneDX
        run: |
          /tmp/parlay ecosystems enrich \
            augmented-litemv-sbom.cdx.json > /tmp/enriched-litemv-sbom.cdx.json

      - name: Enrich SPDX
        run: |
          /tmp/parlay ecosystems enrich \
            augmented-litemv-sbom.spdx.json > /tmp/enriched-litemv-sbom.spdx.json

      - name: Upload Enriched SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: enriched-sboms
          path: |
            /tmp/enriched-litemv-sbom.spdx.json
            /tmp/enriched-litemv-sbom.cdx.json

  Verify:
    needs: Enrich
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download SBOMs
        uses: actions/download-artifact@v4
        with:
          name: enriched-sboms

      - name: Install sbomqs
        run: |
          curl -L -o /tmp/sbomqs \
            "https://github.com/interlynk-io/sbomqs/releases/download/v${SBOMQS_VERSION}/sbomqs-linux-amd64"
          chmod +x /tmp/sbomqs

      - name: Display SBOM Quality Score
        run: |

          for sbom in *.json; do
            echo "Scoring $sbom"
            /tmp/sbomqs score -b "$sbom"
          done

  Upload:
    needs: Enrich
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download SBOMs
        uses: actions/download-artifact@v4
        with:
          name: enriched-sboms

      - name: Install sbommv
        run: |
          curl -L -o /tmp/sbommv \
            "https://github.com/interlynk-io/sbommv/releases/download/v${SBOMMV_VERSION}/sbommv-linux-amd64"
          chmod +x /tmp/sbommv

      - name: Move SBOM to Interlynk Platform
        env:
          INTERLYNK_SECURITY_TOKEN: ${{ secrets.INTERLYNK_SECURITY_TOKEN }}

        run: |
          /tmp/sbommv transfer \
          --input-adapter=folder \
          --in-folder-path="./" \
          --output-adapter=interlynk \
          --out-interlynk-project-name=${TOOL_NAME} \
          --out-interlynk-project-env=${SBOM_ENV}
          --out-interlynk-url="https://api.interlynk.io/lynkapi" --dry-run
          
          /tmp/sbommv transfer \
          --input-adapter=folder \
          --in-folder-path="./" \
          --output-adapter=interlynk \
          --out-interlynk-project-name=${TOOL_NAME} \
          --out-interlynk-project-env=${SBOM_ENV}
          --out-interlynk-url="https://api.interlynk.io/lynkapi"

  Release:
    needs: [Verify, Generate]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Enriched SBOMs
        uses: actions/download-artifact@v4
        with:
          name: enriched-sboms

      - name: Upload SBOMs to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            enriched-sboms/enriched-litemv-sbom.spdx.json
            enriched-sboms/enriched-litemv-sbom.cdx.json
